version: '3.7'

# http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
services:
  web:
    # latest when writing
    # image: nginx:1.17.6-alpine
    image: nginx:alpine
    networks:
      - network-php
    ports:
      - '8080:80'
    volumes:
      # Project files, bind mount for dev (allow files updates on refresh)
      - type: bind
        source: ./src
        # Custom src path in container
        # Nginx custom conf in HOST/config/nginx1.17.6-alpine/sites-enabled/site.conf
        target: /home/www
      # Replace nginx default conf with blank file to prevent localhost:80 conflict
      - type: bind
        source: ./config/nginx1.17.6-alpine/etc/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
      # Config override
      # Automatically loaded thanks to default nginx.conf > 'include /etc/nginx/conf.d/*.conf;'
      - type: bind
        source: ./config/nginx1.17.6-alpine/etc/nginx/conf.d/site.conf
        target: /etc/nginx/conf.d/site.conf
  
  phpfpm:
    # latest when writing
    # image: 'php:7.4.1-fpm'
    image: 'php:fpm'
    networks:
      - network-php
    volumes:
      # Project files, bind mount for dev
      # Php-fpm needs access to sources files to, else he can't access them due to containerisation
      - type: bind
        source: ./src
        target: /home/www

networks:
  network-php: