version: '3.7'

services:
  helloworld:
    deploy:
      endpoint_mode: vip
      labels:
        - "traefik.docker.network=traefik-public"
        - "traefik.enable=true"
        - "traefik.http.routers.helloworld.rule=Host(`test.masamune.fr`)"
        - "traefik.http.services.helloworld.loadbalancer.server.port=80"
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        delay: 0s
        failure_action: pause
        max_failure_ratio: 0
        monitor: 0s
        order: stop-first
        parallelism: 1
      update_config:
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0
        monitor: 0s
        order: stop-first
        parallelism: 1
    image: tutum/hello-world:latest
    networks:
      - traefik-public

  helloworld2:
    deploy:
      endpoint_mode: vip
      labels:
        - "traefik.docker.network=traefik-public"
        - "traefik.enable=true"
        # Test container on dedicated sub folders
        # http://test.masamune.fr/sub/
        - "traefik.http.routers.helloworld2.rule=(Host(`test.masamune.fr`) && PathPrefix(`/sub`))"
        # Strip prefix to allow correct assets path
        #   https://docs.traefik.io/v2.0/middlewares/overview/
        #   https://docs.traefik.io/v2.0/middlewares/stripprefix/
        # Create a middleware named 'helloworld2pathstrip' that strips the prefix '/sub', added in routers.helloworld2.rule ^
        - "traefik.http.middlewares.helloworld2pathstrip.stripprefix.prefixes=/sub"
        # Apply the middleware 'helloworld2pathstrip' to routers.helloworld2
        - "traefik.http.routers.helloworld2.middlewares=helloworld2pathstrip@docker"
        - "traefik.http.services.helloworld2.loadbalancer.server.port=80"
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        delay: 0s
        failure_action: pause
        max_failure_ratio: 0
        monitor: 0s
        order: stop-first
        parallelism: 1
      update_config:
        delay: 10s
        failure_action: pause
        max_failure_ratio: 0
        monitor: 0s
        order: stop-first
        parallelism: 1
    image: tutum/hello-world:latest
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true